role: P1
topology: lan-deployment.yaml
tls:
  ca: ../../lan-secrets/ca.pem
  certificate: ../../lan-secrets/p1.pem
  private_key: ../../lan-secrets/p1.key
timeouts:
  startup: 30
  step: 30
  shutdown: 5
