role: P2
topology: lan-deployment.yaml
tls:
  ca: ../../lan-secrets/ca.pem
  certificate: ../../lan-secrets/p2.pem
  private_key: ../../lan-secrets/p2.key
timeouts:
  startup: 30
  step: 30
  shutdown: 5
